# Generated by Django 2.2.6 on 2019-11-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_identifier', '0004_auto_20191109_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='speed',
        ),
    ]
