var canvas = document.getElementById('canvas');
var context = canvas.getContext('2d');
var snakeSize = 10;
var w = 650;
var h = 500;
var score = 0;
var obs = [];
var snake;
var snakeSize = 10;
var food;